### ISSUE TITLE
warcio.exceptions.ArchiveLoadFailed: Unknown archive format

### ISSUE THREAD

**Issue by KyloPrem** [webrecorder/warcio#144]
Hey guys, I am trying to replicate the results of a paper [Project](https://github.com/trtm/AURC/blob/master/src/download.py) for which I need to download data and format it their way.  I receive the following error message which I have trouble with. I am not sure if the data just cannot be found, or if the file has the wrong format. Any ideas on how I can analyze objects generated with ArchiveIterator? 

```
Traceback (most recent call last):
  File "download.py", line 88, in <module>
    main()
  File "download.py", line 63, in main
    uri, page = download_page(CommonCrawlData)
  File "download.py", line 26, in download_page
    for record in ArchiveIterator(raw_data, arc2warc=True):
  File "/home/x/.local/lib/python3.6/site-packages/warcio/archiveiterator.py", line 110, in _iterate_records
    self.record = self._next_record(self.next_line)
  File "/home/x/.local/lib/python3.6/site-packages/warcio/archiveiterator.py", line 262, in _next_record
    self.check_digests)
  File "/home/x/.local/lib/python3.6/site-packages/warcio/recordloader.py", line 88, in parse_record_stream
    known_format))
  File "/home/x/.local/lib/python3.6/site-packages/warcio/recordloader.py", line 243, in _detect_type_load_headers
    raise ArchiveLoadFailed(msg + str(se.statusline))
warcio.exceptions.ArchiveLoadFailed: Unknown archive format, first line: ['<?xml', 'version="1.0"', 'encoding="UTF-8"?>']
```
[EDIT] I am using python 3.6.9 with the following libraries:

```
certifi==2021.10.8
chardet==3.0.4
idna==2.10
jusText==2.2.0
lxml==4.8.0
numpy==1.19.5
pandas==1.0.3
pkg-resources==0.0.0
python-dateutil==2.8.2
pytz==2022.1
requests==2.23.0
six==1.16.0
tqdm==4.45.0
urllib3==1.25.11
warcio==1.7.3
```

**Comment by wumpus** [comment]
From the first line printed in the exception, you can see that the file you're asking ArchiveIterator to work on is xml.

ArchiveIterator iterates over warc files. Not xml.

**Comment by KyloPrem** [comment]
That is interesting. The data .tsv definitely references the common crawl archives.
https://commoncrawl.org/2017/07/july-2017-crawl-archive-now-available/
 `crawl-data/CC-MAIN-2016-07/segments/1454702018134.95/warc/CC-MAIN-20160205195338-00121-ip-10-236-182-209.ec2.internal.warc.gz`

I tried to build a minimal example below, which gave me the above exception
```
import io
import time
import justext
import argparse
import requests
import pandas as pd
from tqdm import tqdm
from warcio.archiveiterator import ArchiveIterator


def download_debug():

    common_crawl_data = {"filename":"crawl-data/CC-MAIN-2016-07/segments/1454702018134.95/warc/CC-MAIN-20160205195338-00121-ip-10-236-182-209.ec2.internal.warc.gz",
                         "offset":244189209,
                         "length":989
                         }

    offset, length = int(common_crawl_data['offset']), int(common_crawl_data['length'])
    offset_end = offset + length - 1

    prefix = 'https://commoncrawl.s3.amazonaws.com/'

    resp = requests.get(prefix + common_crawl_data['filename'], headers={'Range': 'bytes={}-{}'.format(offset, offset_end)})
    raw_data = io.BytesIO(resp.content)

    uri = None
    page = None
    print("hallo")
    for record in ArchiveIterator(raw_data, arc2warc=True):
        uri = record.rec_headers.get_header('WARC-Target-URI')
        R = record.content_stream().read()
        try:
            page = R.strip().decode('utf-8')
        except:
            page = R.strip().decode('latin1')
        print(uri, page)
    return uri, page

download_debug()
```
any recommendation on how to debug this or an idea why this function would return a xml instead of the warc file?

**Comment by wumpus** [comment]
@KyloPrem so just to be clear, you closed this because the actual issue is receiving a 403 rate limit result, and not checking the http status.  We did make a change that causes this recently, and honestly, I didn't even think of that when I read your bug report! Glad you figured it out.
