### ISSUE TITLE
webrecorder fails to open IA warc file on MacOS X Ventura 13.2.1

### ISSUE THREAD

**Issue by theopathic** [webrecorder/warcio#151]
Attempting to open a IA warc file

https://archive.org/details/perma_cc_CJ5W-XY7X

on MacOS X Ventura 13.2.1 hangs.  Going to "About" and looking at "Additional Debug Info" gives

stderr: [30860] Failed to execute script webrecorder_player

stderr: Traceback (most recent call last):
File "webrecorder/standalone/webrecorder_player.py", line 13, in 
File "/Users/travis/.pyenv/versions/3.6.8/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
File "webrecorder/standalone/serializefakeredis.py", line 8, in 
File "/Users/travis/.pyenv/versions/3.6.8/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
File "fakeredis.py", line 105, in 
ImportError: fakeredis: unable to find libc or equivalent

**Comment by ikreymer** [comment]
It seems like you are using Webrecorder Player, which is no longer being supported.
You should be able to open the WARC using https://replayweb.page/ or the desktop app from https://github.com/webrecorder/replayweb.page/releases
(Also, this repository is for the warcio project, which is a low-level library for reading WARC files, different than the tools mentioned above)

**Comment by ikreymer** [comment]
The specific WARC you mentioned is actually from perma.cc, and you can access the original from:
https://perma.cc/CJ5W-XY7X which uses the same replayweb.page viewer. (You can also download the WARC from there).
